<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-06 at 10:21:52.
 */
class KataTennisTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var KataTennis
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include_once '../kataTennis.php';
        $this->object = new KataTennis;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    
    
}
